version: '3.8'

services:
  energy-analysis:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: energy-analysis-app
    ports:
      - "5000:5000"
    volumes:
      - ../Model:/app/Model:ro
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    restart: unless-stopped 